const types = {
  FETCH_YOUTUBE_RESULTS: "FETCH_YOUTUBE_RESULTS",
  FETCH_WIKI_RESULTS: "FETCH_WIKI_RESULTS",
  SET_CURRENT_VIDEO: "SET_CURRENT_VIDEO",
  SET_THEME: "SET_THEME",
  HANDLE_LOGIN: "HANDLE_LOGIN",
  HANDLE_SIGNUP: "HANDLE_SIGNUP"
};
export default types;
