const types = {
  FETCH_YOUTUBE_RESULTS: "FETCH_YOUTUBE_RESULTS",
  FETCH_WIKI_RESULTS: "FETCH_WIKI_RESULTS",
  SET_CURRENT_VIDEO: "SET_CURRENT_VIDEO",
  SET_THEME: "SET_THEME",
  HANDLE_LOGIN: "HANDLE_LOGIN",
  HANDLE_SIGNUP: "HANDLE_SIGNUP",
  SAVE_TO_HISTORY: "SAVE_TO_HISTORY",
  CLEAR_HISTORY: "CLEAR_HISTORY",
  GET_USER_DB: "GET_USER_DB"
};
export default types;
